language: python

matrix:
    include:
        # 64-bit Linux builds
        - os: linux
          python: 3.6
        - os: linux
          python: 3.7
        - os: linux
          python: 3.8
          env: RUN_FLAKE=1

cache:
    - pip

before_install:
    - chmod +x ./ci/travis_install.sh
    - chmod +x ./ci/travis_run.sh

install:
    - ./ci/travis_install.sh

script:
    - ./ci/travis_run.sh
