environment:
    matrix:
        - PYTHON: "C:\\Python36-x64"
        - PYTHON: "C:\\Python37-x64"
        - PYTHON: "C:\\Python38-x64"
          RUN_FLAKE: "1"

install:
    - "if \"%RUN_FLAKE%\"==\"1\" %PYTHON%\\python.exe -m pip install flake8"
    - "%PYTHON%\\python.exe -m pip install wheel"
    - "ci\\win_build.cmd %PYTHON%\\python.exe setup.py build"
    - "ci\\win_build.cmd %PYTHON%\\python.exe setup.py develop"

build: off

test_script:
    - "%PYTHON%\\python.exe ttasks.py test"
    - "if \"%RUN_FLAKE%\"==\"1\" %PYTHON%\\Scripts\\flake8.exe ."

after_test:
    - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
    - path: dist\*
